version: '2.1'
services:
  nginx:
      build: ./nginx
      links:
          - my-its1:my-its1
      ports:
          - "80:80"
  my-its1:
    image: javajigi/its:latest
    ports:
      - "9090:9090"
    links:
      - scouter-server
  scouter-server:
   image: zealiard/scouter:latest
   ports:
     - "6100:6100"
     - "6100:6100/udp"