version: '2.1'
services:
  my-its:
    image: javajigi/its:latest
    ports:
      - "9090:9090"
    links:
      - scouter-server
  scouter-server:
   image: zealiard/scouter:latest
   ports:
     - "6100:6100"
     - "6100:6100/udp"