version: "2"
volumes:
  data-jenkins:
    driver: "local"
services:
  jenkins:
    build: ./jenkins
    ports:
      - "7070:8080"
      - "50000:50000"
    restart: "always"
    volumes:
      - "data-jenkins:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"