version: '2.1'
services:
  controller:
    image: ngrinder/controller
    ports:
      - "16001:16001"
      - "12000-12009:12000-12009"
      - "7000:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
  agent1:
    image: ngrinder/agent
    depends_on:
      controller:
        condition: service_healthy
    environment:
      - CONTROLLER_ADDR=controller:80
  agent2:
    image: ngrinder/agent
    depends_on:
      controller:
        condition: service_healthy
    environment:
      - CONTROLLER_ADDR=controller:80
  agent3:
    image: ngrinder/agent
    depends_on:
      controller:
        condition: service_healthy
    environment:
      - CONTROLLER_ADDR=controller:80
